version: '3.9'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  api:
    container_name: server
    build: .
    image: payengine/server
    depends_on:
      - db
    ports:
      - "5000:5000"
